In [14]:
import numpy as np

# Generate a random rectangular matrix A
A = np.random.rand(3, 3)
print("Matrix A = \n", A)

Matrix A = 
 [[0.44187297 0.30546139 0.95536498]
 [0.36821453 0.91635344 0.15594541]
 [0.9253704  0.70782862 0.16938634]]


In [15]:
# Rank of A
rankA = np.linalg.matrix_rank(A)
print("Rank of A = ", rankA)

Rank of A =  3


In [16]:
# Trace of A
traceA = np.trace(A)
print("Trace of A = ", traceA)

Trace of A =  1.527612759431411


In [17]:
# Determinant of A
if A.shape[0] == A.shape[1]:
    detA = np.linalg.det(A)
    print("Determinant of A = ", detA)
else:
    print("A is not a square matrix. Determinant is not defined.")

Determinant of A =  -0.5162779761057099


In [18]:
# Inverse of A
if A.shape[0] == A.shape[1] and detA != 0:
    invA = np.linalg.inv(A)
    print("Inverse of A = \n", invA)
else:
    print("A is not a square matrix or Determinant of A is 0. Inverse does not exist.")

Inverse of A = 
 [[-0.08684301 -1.20960745  1.60343211]
 [-0.15870666  1.56740994 -0.54790485]
 [ 1.1376305   0.0583124  -0.56643225]]


In [19]:
# Eigenvalues and eigenvectors of A'A and AA'
AtA = np.transpose(A) @ A
AAt = A @ np.transpose(A)
eigvals_AtA, eigvecs_AtA = np.linalg.eig(AtA)
eigvals_AAt, eigvecs_AAt = np.linalg.eig(AAt)

print(" eigvals_AtA = ", eigvals_AtA, "\n", "eigvecs_AtA = \n", eigvecs_AtA)
print("\n")
print(" eigvals_AAt = ", eigvals_AAt, "\n", "eigvecs_AAt = \n", eigvecs_AAt)

 eigvals_AtA =  [2.82333339 0.15517207 0.60840318] 
 eigvecs_AtA = 
 [[ 0.62019582  0.77641404 -0.1119749 ]
 [ 0.66767021 -0.59739763 -0.44422129]
 [ 0.41179319 -0.20074188  0.88889204]]


 eigvals_AAt =  [2.82333339 0.60840318 0.15517207] 
 eigvecs_AAt = 
 [[ 0.51860951  0.85133776 -0.07917188]
 [ 0.53824688 -0.39701929 -0.74341508]
 [ 0.66433009 -0.34292811  0.66412788]]


### What interesting differences can you notice between both?
The **eigvals** are the same values, however in some cases the terms change position.
The **eigvecs** are very different, which explains that for this case AtA and AAt are not the same